services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: reporover_backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: reporover_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped